server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      resolve-lazily: true
      file-size-threshold: 2147483647
  tomcat:
    max-swallow-size: 1GB
    max-http-post-size: 1GB
    max-connections: 200
    threads:
      max: 200

spring:
  application:
    name: TeleShare-API
  datasource:
    url: jdbc:mysql://localhost:3306/teleshare?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

telegram:
  api-id: ${TELEGRAM_API_ID}
  api-hash: ${TELEGRAM_API_HASH}
  phone-number: ${TELEGRAM_PHONE}
  storage-channel-id: ${TELEGRAM_STORAGE_CHANNEL}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  file-retention-days: 7
  max-downloads-per-file: 50
  max-uploads-per-hour-per-ip: 5
  allowed-file-types: image/jpeg,image/png,image/gif,application/pdf,text/plain,application/zip,video/mp4,audio/mpeg,application/json,application/xml

logging:
  level:
    com.teleshare: INFO
    org.springframework.web: INFO
    it.tdlight: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

